### PR TITLE
ci: change workflows to use reusable action for looker versions

### PR DESCRIPTION
**Pull request by drstrangelooker**
The looker versions for CI are all in one place now.

### CODE REVIEW

**Review by jkaster — APPROVED** [review]
LGTM. Nice improvement

**Comment by drstrangelooker** [comment]
@jkaster Typescript tests fail with 22.4 on an issue with strings passed where interferes are expected.

I'm thinking that I'll override the required check then we'll do a separate PR to change the tests.

**Comment by drstrangelooker** [comment]
@jkaster I backed the supported-versions array to `["21.18", "21.20", "22.0", "22.2"]` for now.

I also changed the action to reference `supported-versions@main` instead of `supported-versions@v0.0.1`. I realized if I used a specific tag, I would need to change `sdk-codegen` every time the version array was changed. That was the exact opposite of what we wanted. So I needed to reference the main branch instead.

I also created tags `supported-versions-v22.2` and `supported-versions-v22.4` to allow a caller to specify the max version they want to deal with.

**Comment by jkaster** [comment]
> @jkaster Typescript tests fail with 22.4 on an issue with strings passed where interferes are expected.

I think you mean "integers" above, and I'll look at that.

**Pull request merged**
