### PR TITLE
feat: generate Kotlin SDK for Looker 23.20

### PR DESCRIPTION
**Pull request by tjbanghart**
Bumping the Kotlin SDK to match Looker v23.20.

23.18 added SQL Interface endpoints which are needed for several use cases in the Looker JDBC Driver (see https://github.com/looker-open-source/calcite-avatica/commit/dbe2821c0c75f290cf729fad875e41827570d64d).

### CODE REVIEW

**Review by jkaster — COMMENTED** [review]
This is typically part of a generation process DevRel does for all SDKs every release. Are you needing to sync it earlier than their usual schedule, which is next week?

**Comment by tjbanghart** [comment]
Oh, thanks @jkaster! Would be nice to have it earlier but it can wait for the release process.

**Comment by tjbanghart** [comment]
Ah I see, looks like 23.18 commit was reverted: https://github.com/looker-open-source/sdk-codegen/commit/680c7ec85ca4e34746994b4b44db0928e8caf0e8

**Comment by jkaster** [comment]
there is other work by @deanlooker that will land 23.18 for all SDKs. He's removing all 3.x references

**Comment by deanlooker** [comment]
Hey @tjbanghart , is there anything unique to this change that wouldn't be covered in the automated sdk release stuff here? https://github.com/looker-open-source/sdk-codegen/pull/1402

**Comment by tjbanghart** [comment]
Nah, closing this. Thanks!

**Pull request closed without merging**
