### PR TITLE
feat: add 2 Python examples (pause/copy schedules, kill queries)

### PR DESCRIPTION
**Pull request by lanlooker**
Hi team, I am adding two new examples for the Python SDK:

- Schedule Management: Pause/resume schedules + Copy/migrate schedules 
- Kill queries 

Tagging @joeldodge79 and @josephaxisa -- thank you for reviewing

### CODE REVIEW

**Comment by joeldodge79** [comment]
@lanlooker thanks! can you add links from `examples/python/README.md` ?

**Review by joeldodge79 — CHANGES_REQUESTED** [review]
add links from examples/python/README.md

**Comment by lanlooker** [comment]
Hi @joeldodge79 ! I edited  `examples/python/README.md`

1. Added the two new examples link
2. Changed the section wording to align with our API Looker doc 
3. Added the link to our API references

**Review by josephaxisa — APPROVED** [review]
Looks great, thanks @lanlooker!

**Review by joeldodge79 — APPROVED** [review]
👍

**Pull request merged**
