### PR TITLE
fix: Fix ignorant json decoding

### LINKED ISSUE #911: Go GitDeployKey and CreateGitDeployKey do not return a deploy key
Somehow the response is always assumed to be JSON, and somehow the calls to `GitDeployKey` and `CreateGitDeployKey` always return an empty string `""`.

See https://github.com/looker-open-source/sdk-codegen/blob/main/go/rtl/auth.go#L142

This needs to be fixed, because otherwise the go client cannot create or read git deploy keys.

#### err is not checked

When I properly check and return `err`, I get `invalid character 's' looking for beginning of value` when calling `GitDeployKey`.

```diff
diff --git a/go/rtl/auth.go b/go/rtl/auth.go
index 836d4aca..46a26b73 100644
--- a/go/rtl/auth.go
+++ b/go/rtl/auth.go
@@ -133,14 +134,19 @@ func (s *AuthSession) Do(result interface{}, method, ver, path string, reqPars m
                return err
        }
        defer res.Body.Close()

        if res.StatusCode < 200 || res.StatusCode > 226 {
                return fmt.Errorf("response error: %s", res.Status)
        }

        err = json.NewDecoder(res.Body).Decode(&result)
-
+       if err != nil {
+               return err
+       }
        return nil
 }

```

### PR DESCRIPTION
**Pull request by lukas-at-harren**
* Return an error on invalid json
* Only attempt to decode json for application/json responses
* Return the full response body for any other responses if the interface is a string

## Developer Checklist [ℹ️](https://github.com/looker-open-source/sdk-codegen/blob/main/CONTRIBUTING.md#developer-checklist)

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/looker-open-source/sdk-codegen/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [?] Ensure the tests and linter pass
- [x] Appropriate docs were updated (if necessary)

Fixes #911  🦕

### CODE REVIEW

**Comment by lukas-at-harren** [comment]
Hi, small bump, do you think this PR can be merged back into mainstream?

At another place, I am using this SDK in order to talk to the Looker API, and the bugs in the current Go-SDK prevent me from using crucial features I have implemented over there: https://github.com/hirosassa/terraform-provider-looker/pull/15

If I can be of any help, let me know. I don't know what "cla: no" means.

**Comment by drstrangelooker** [comment]
For the cla, you need to register a google "Contributor License Agreement". https://cla.developers.google.com/

**Comment by drstrangelooker** [comment]
@jeremytchang can you look at this and resolve the merge conflicts, then see if this makes sense?

**Comment by lukas-at-harren** [comment]
I did already sign the CLA.

**Comment by lukas-at-harren** [comment]
Regarding the merge conflicts:

From my side it should be noted, that only JSON-type responses (as stated in the content type) should get JSON-decoded. Looker has some endpoints that do not respond in JSON (as its noted in the content type) and therefore the SDK fails to handle those API endpoints.

It seems to me, that in the meantime somebody already edited parts of that code, so a merge is necessary.

**Comment by lukas-at-harren** [comment]
@jeremytchang bump, can you have a look at this PR please? I did sign the CLA and I see no issues from my side with the contribution.

This is actually needed downstream https://github.com/hirosassa/terraform-provider-looker/pull/15 to fully support some features on the hirossa/looker Terraform provider.
And the way this API client is implemented prohibits the usage of some API endpoints from Looker.

I would appreciate some attention on this PR.

**Comment by jeremytchang** [comment]
Hi @lukas-at-harren!
Sorry for the getting back to you late. I've put up a PR that fixes this more broadly. https://github.com/looker-open-source/sdk-codegen/pull/1021
I appreciate you looking into this and putting up a PR! While looking/testing your PR I discovered that we cannot parse according to content-type _and_ result type for methods that return union types like `RunQuery`. This will break as the json decoder expects a `string` type result. 

I have also created an issue around better supporting union types in Go SDK. https://github.com/looker-open-source/sdk-codegen/issues/1022 Would love your input!

May I close this PR?

**Comment by lukas-at-harren** [comment]
@jeremytchang thanks for picking this up again. Much appreciated. I will checkout #911 and if it works downstream (using the go looker-sdk in hirosassa terraform provider), I am pretty sure we can close this one.

**Comment by jeremytchang** [comment]
Fixed by this merged PR. https://github.com/looker-open-source/sdk-codegen/pull/1021

**Pull request closed without merging**
