### PR TITLE
chore: Added bundle step and cleaned up hackathon CI

### PR DESCRIPTION
**Pull request by jeremytchang**
- Added `yarn bundle` step to make sure hackathon can always be bundled
- Renamed and split up steps to be more descriptive

### CODE REVIEW

**Review by jkaster — CHANGES_REQUESTED** [review]
I think this  may run on every PR as written. See the other workflow files for how they limit the scope of CI to the affected paths.

**Comment by jeremytchang** [comment]
@jkaster This workflow should already only run on wholly-sheet and hackathon path only. Unless i'm misunderstanding this `on` [section](https://github.com/looker-open-source/sdk-codegen/blob/main/.github/workflows/hackathon-ci.yml#L2) this existing workflow should be limited in scope already.

Also if that was the case, the checks for this PR would have already run the Hackathon CI too, but it has not.

**Comment by jeremytchang** [comment]
Also this is only adding steps to the original hackathon CI workflow Bryan and you approved/merged before.

**Review by jkaster — APPROVED** [review]
LGTM

**Pull request merged**
