### PR TITLE
docs: Fixed missing quote in Python SDK README example

### LINKED ISSUE #561: Python SDK README error
There seems to be a missing double quote around `last_name` in the example [here](https://github.com/looker-open-source/sdk-codegen/blame/main/python/README.rst#L36) 

```
sdk.create_user(body={"first_name": "Jane", last_name: "Doe"})
```
PR to fix: https://github.com/looker-open-source/sdk-codegen/pull/560

### PR DESCRIPTION
**Pull request by hkhoa**
Fix Python SDK README

## Developer Checklist [ℹ️](https://github.com/looker-open-source/sdk-codegen/blob/main/CONTRIBUTING.md#developer-checklist)

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/looker-open-source/sdk-codegen/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [x] Appropriate docs were updated (if necessary)

Fixes #561 https://github.com/looker-open-source/sdk-codegen/issues/561 🦕

### CODE REVIEW

**Comment by joeldodge79** [comment]
@googlebot rescan

**Comment by joeldodge79** [comment]
hi @hkhoa, thanks for fixing this! Once you sign the CLA I'll merge it (don't worry about tests on this one)

**Comment by hkhoa** [comment]
@googlebot I signed it!

**Comment by hkhoa** [comment]
Thanks @joeldodge79. CLA CI passed now

**Review by joeldodge79 — APPROVED** [review]

**Pull request merged**
