### PR TITLE
feat: Updating ktor version for user level mobile access

### LINKED ISSUE #821: Update ktor library
Update the ktor library from 1.4.2 to 1.5.4
1.4.2 doesn't seem to be capturing error json from the response if it's not 200
1.5.4 This is working fine.

Updating it since we need to capture error from user level mobile access 
https://b.corp.google.com/issues/196757891

### PR DESCRIPTION
**Pull request by Aatish-Molasi**
Update the ktor library from 1.4.2 to 1.5.4
1.4.2 doesn't seem to be capturing error json from the response if it's not 200
1.5.4 This is working fine.

Updating it since we need to capture error from user level mobile access
https://b.corp.google.com/issues/196757891

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/looker-open-source/sdk-codegen/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Appropriate docs were updated (if necessary)

Fixes #821  🦕

### CODE REVIEW

**Review by kalenp — APPROVED** [review]
LGTM Seems straightforward enough.

**Review by jkaster — COMMENTED** [review]
`bin/smoke kotlin` doesn't pass. If this change works for mobile purposes it's fine to proceed and we'll make a separate PR for the failing tests.

**Comment by Aatish-Molasi** [comment]
@jkaster this seems to be an existing issue on the current main branch
Screen Shot 2021-09-17 at 11 14 18 AM

Have created a separate ticket that's being looked into by @mistryrakesh 
https://github.com/looker-open-source/sdk-codegen/issues/825

**Comment by jkaster** [comment]
Thanks so much for checking if the main branch had that issue as well. @joeldodge79 looks like we need to add Kotlin smoke tests to CI when #825 lands.

**Pull request merged**
