### PR TITLE
feat: Added unit test CI for Go SDK

### PR DESCRIPTION
**Pull request by jeremytchang**
Smoke test to come soon after adding environment variable support to Go SDK.

### CODE REVIEW

**Comment by jeremytchang** [comment]
@drstrangelooker @jkaster Confirmed workflow works locally and also in Github. 
Will follow up with smoke tests in another PR after i _first_ push up a PR implementing LOOKERSDK_* env variable handling.

**Comment by jeremytchang** [comment]
@drstrangelooker If possible can you make the go test check a required check, or give me permissions to add that.

**Comment by jkaster** [comment]
Because we're behind schedule launching 22.0 I'd like to wait on this PR until after 22.0 is out

**Comment by drstrangelooker** [comment]
I rebased this on master and forced pushed it.

**Comment by drstrangelooker** [comment]
@jkaster I'm thinking about merging this but not making the go tests required until after shipping 22.0. Thoughts?

**Review by drstrangelooker — APPROVED** [review]
LGTM

**Comment by jkaster** [comment]
> @jkaster I'm thinking about merging this but not making the go tests required until after shipping 22.0. Thoughts?

@drstrangelooker that sounds good to me. I just didn't want it blocking deployment of other SDKs right now. Thanks!

**Pull request merged**
