### PR TITLE
Fix deprecations in python-ci action

### PR DESCRIPTION
**Pull request by drstrangelooker**

### CODE REVIEW

**Comment by drstrangelooker** [comment]
@jeremytchang this PR resolves all the deprecation notices for the Python-CI Github Action. It should be merged in soon, but can wait until after the SDK is released. Or it can go right away. Your choice.

**Review by jeremytchang — APPROVED** [review]
Approved though can we somehow trigger python CI against this PR first? It contains multiple major version bumps to our action dependencies. Want to make sure the python CI will run correctly, unless you've already tested it locally.

**Comment by jeremytchang** [comment]
And lets merge after the SDK gen goes in.

**Review by jeremytchang — CHANGES_REQUESTED** [review]
Actually what do you think of adding a path to this workflow file in this file so we'll always trigger CI if it shows up in a PR. Can we do that?
```
on:
  pull_request:
    paths:
      - python/**
      - .github/workflows/python-ci.yml
      ```

**Comment by drstrangelooker** [comment]
@jeremytchang I already manually triggered it here: https://github.com/looker-open-source/sdk-codegen/actions/runs/4296565881 It succeeds fine.

**Comment by drstrangelooker** [comment]
I can do I think. Let me check.

**Review by jeremytchang — DISMISSED** [review]

**Comment by jeremytchang** [comment]
I approved either way, because i didn't know you can run a workflow directly against a branch of your choosing in the UI. The additional path is a nice to have.

**Review by jeremytchang — APPROVED** [review]

**Pull request merged**
