### PR TITLE
fix: add missing bumper method to ICodeGen

### PR DESCRIPTION
**Pull request by josephaxisa**

### CODE REVIEW

**Review by joeldodge79 — CHANGES_REQUESTED** [review]
here come the commit police...

we don't need to strictly follow the [angular commit convention](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-header) but it's sort of an "industry" standard in this space:

the `<short summary>` section (after type/scope) states:
> Summary in present tense. Not capitalized. No period at the end.

**Comment by jkaster** [comment]
Funny switch to our commit comment practice. I'll update my in-flight PR #578 also

**Comment by josephaxisa** [comment]
Looks like `main` is broken. Failures are unrelated to my changes

**Review by bryans99 — APPROVED** [review]
LGTM

**Pull request merged**
