### PR TITLE
Add python 3.6 support

### PR DESCRIPTION
**Pull request by ZhongRabbit**

### CODE REVIEW

**Comment by joeldodge79** [comment]
We're going to add support for 3.6 soon - but we need to update the code generator as the patches you supplied on are generated files. I'll update you here when it's released

**Comment by ZhongRabbit** [comment]
Hi @joeldodge79, appreciate your incorporating Python 3.6.
Any update on the timeline of this?

**Comment by jkaster** [comment]
@joeldodge79 is currently working on the PR for this, so it shouldn't be more than a week or two.

**Comment by joeldodge79** [comment]
@ZhongRabbit sorry, I meant to update you - here's the PR: https://github.com/looker-open-source/sdk-codegen/pull/225

**Comment by joeldodge79** [comment]
python3.6 is now available as of [0.1.3b13](https://pypi.org/project/looker-sdk/)

**Pull request closed without merging**
