### PR TITLE
feat: generate SDKs for Looker 23.18

### PR DESCRIPTION
**Pull request by drstrangelooker**
Release-As: 23.18.0

### CODE REVIEW

**Comment by drstrangelooker** [comment]
@jeremytchang @jkaster can you take a look at what is failing here?

**Comment by jkaster** [comment]
> @jeremytchang @jkaster can you take a look at what is failing here?

@treshugart or @josephaxisa may be able to help

**Comment by josephaxisa** [comment]
The issue is because `apix-files` is being considered a workspace as per the change in #1370. Perhaps `/apix-files` is incomplete and requires additional config files. cc @treshugart

**Comment by deanlooker** [comment]
lgtm

**Review by deanlooker — APPROVED** [review]

**Pull request merged**
